name: Suicide
version: '${project.version}'
description: Kills the command sender
authors: [MCUmbrella]
website: https://github.com/MSUPlugins/Suicide
main: vip.floatationdevice.msu.suicide.SuicidePlugin
api-version: 1.13
depend:
  - MSUCore
commands:
  suicide:
    description: "Kill the command sender"
permissions:
  suicide.suicide:
    description: "Allows the player to use /suicide"
    default: true
